version: "3"
services:
  skkubot:
    platform: linux/amd64
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    container_name: skkubot-devcontainer
    ports:
      - 3000:3000
    # ...
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000

volumes:
  index_data:
    driver: local
  backups:
    driver: local
