version: "3"
services:
  python-api:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bookworm
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    links:
      - app
    # ...

  app:
    platform: linux/amd64
    build:
      context: ./.devcontainer/app-container
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace:cached
    command: sleep infinity
    container_name: skkubot-devcontainer
    # ...
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000

volumes:
  index_data:
    driver: local
  backups:
    driver: local
