/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FgudXG0UHzA
 */
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Chatbot() {
  return (
    <div className="grid h-[600px] min-h-[400px] w-full max-w-screen-lg mx-auto items-stretch border border-gray-200 rounded-lg shadow-lg dark:border-gray-800 dark:border-gray-800">
      <div className="grid w-full border-b border-gray-200 p-6 items-start dark:border-gray-800">
        <div className="grid gap-2">
          <h1 className="text-xl font-bold">Chat with Support</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">
            You are chatting with a support agent. How can we help you today?
          </p>
        </div>
      </div>
      <div className="grid w-full p-6 items-start gap-4">
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
        <div className="grid gap-2">
          <div className="grid gap-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        You: '}
                        Can I change my subscription plan?
                      `}
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              {`
                        Support Bot: '}
                        You can change your subscription plan in the Billing section
                        of your account.
                      `}
            </p>
          </div>
        </div>
      </div>
      <div className="flex w-full border-t border-gray-200 p-6 items-center dark:border-gray-800">
        <Input className="flex-1 min-h-auto" placeholder="Type your message" />
        <Button className="ml-2" size="icon">
          <SendIcon className="h-4 w-4" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>
  );
}

function SendIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  );
}
