# 첫 번째 스테이지: Python 이미지를 사용하여 필요한 파일 준비
FROM --platform=linux/amd64 python:3.10.5-slim-buster as python-base

# 두 번째 스테이지: 최종 이미지 생성
FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:ubuntu-22.04

ARG PYTHON_VERSION=3.10.5
# change apt repository source due to bottleneck of network (#20)
RUN sed -i 's/archive.ubuntu.com/ftp.kaist.ac.kr/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/ftp.kaist.ac.kr/g' /etc/apt/sources.list
# for arm64 apt repository
RUN sed -i 's/ports.ubuntu.com/ftp.kaist.ac.kr/g' /etc/apt/sources.list

# install google-chrome and chromedriver dependencies
RUN apt-get -y update --no-install-recommends \
    && apt-get -y upgrade --no-install-recommends \
    && apt-get -y install --no-install-recommends \
    wget unzip \
    # for pip ssl module
    # openssl \
    # for google-chrome
    fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 \
    libdrm2 libgbm1 libgtk-3-0 libpango-1.0-0 libu2f-udev libvulkan1 libxcomposite1 libxdamage1 \
    libxfixes3 libxkbcommon0 libxrandr2 xdg-utils libnspr4 libnss3\
    # for python
    software-properties-common \
    && apt-get autoremove -y \
    && apt-get clean -y

# SSL 라이브러리 복사
COPY --from=python-base /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/
COPY --from=python-base /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/


# 첫 번째 스테이지에서 Python 복사
COPY --from=python-base /usr/local /usr/local

# Python 환경 변수 설정
ENV PATH="/usr/local/bin:$PATH"
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/local/lib

# set python3.10 as default python3
RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.10 1 \
    && update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.10 1 \
    && update-alternatives --install /usr/bin/pip3 pip3 /usr/local/bin/pip3.10 1